# General Configurations
GPU_ID: '0,1,2,3'
WORKERS: 4

DATASET_NAME: 'birds'
EMBEDDING_TYPE: 'cnn-rnn'
DATA_DIR: './data/birds'
VOCAB_FILENAME: 'cub_vocab.pkl'

# Recurrence related configurations
INITIAL_IMAGE_SIZE: 64
FINAL_IMAGE_SIZE: 256
IMG_IMPRV_STEPS: 3 # 64 -> 128 -> 256
HIDDEN_VEC_SIZE: 100
HIDDEN_STATE_SIZE: 8 # The hidden state will be of dimension 1 x HIDDEN_STATE_SIZE x HIDDEN_STATE_SIZE
HIDDEN_STATE_DEPTH: 8  # Depth of the H-State

# Cross Caption Consistency configurations
ENSURE_CAPTION_CONSISTENCY: True

# Training configurations
TRAIN:
    FLAG: True
    NET_G: '/home/joseph/workspace/aRTISt/output/birds_2018_06_29_05_37_40/model/netG_137400.pth'
    NET_D: '/home/joseph/workspace/aRTISt/output/birds_2018_06_29_05_37_40/model/netD'
    NET_CCCN: '/home/joseph/workspace/aRTISt/output/birds_2018_06_29_05_37_40/model/cccn.pth'
    BATCH_SIZE: 32 # For DGX
    MAX_EPOCH: 4500
    SNAPSHOT_INTERVAL: 200
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    CCCN_LR: 0.0002

# GAN Configurations
GAN:
    EMBEDDING_DIM: 128
    DF_DIM: 64
    GF_DIM: 64
    TEXT_CONDITION: True # Whether the discriminator should be conditioned on text embedding.
